name: RageKitPvP
version: '1.0-SNAPSHOT'
main: ragekitpvp.ragekitpvp.RageKitPvP
api-version: 1.19
commands:
  head:
    description: give head
  kits:
    description: open kits
  setspawn:
    description: sets world spawn point
  flex:
    description: flex your stats!
  ping:
    description: get your ping!
  ip:
    description: gets a players ip
  die:
    description: you die
  randomkit:
    description: get a random kit