name: RageKitPvP
version: '1.0-SNAPSHOT'
main: ragekitpvp.ragekitpvp.RageKitPvP
api-version: 1.19
commands:
  head:
    description: give head
  kits:
    description: open kits
  spawnset:
    description: sets world spawn point
  flex:
    description: flex your stats!
  ping:
    description: get your ping!
  ip:
    description: gets a players ip
  die:
    description: you die
  randomkit:
    description: get a random kit
  resetstats:
    description: resets a players statistics
  reloadstats:
    description: reloads the stats page
  spawn:
    description: sends players to world spawn